<?php

namespace ContainerKFrJr5f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTSInstallCommand_LazyService extends EAdmin_Core_Tests_Fixture_TestKernelTestDebugContainer
{
    /**
     * Gets the private '.EAdmin\Core\Command\TSInstallCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.EAdmin\\Core\\Command\\TSInstallCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('eadmin:ts:install', [], 'Copy EAdmin config files (vite.config.ts, tsconfig.json) into the project root', false, #[\Closure(name: 'EAdmin\\Core\\Command\\TSInstallCommand')] fn (): \EAdmin\Core\Command\TSInstallCommand => ($container->privates['EAdmin\\Core\\Command\\TSInstallCommand'] ?? $container->load('getTSInstallCommandService')));
    }
}
