<?php

namespace ContainerKFrJr5f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTSInstallCommandService extends EAdmin_Core_Tests_Fixture_TestKernelTestDebugContainer
{
    /**
     * Gets the private 'EAdmin\Core\Command\TSInstallCommand' shared service.
     *
     * @return \EAdmin\Core\Command\TSInstallCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/TSInstallCommand.php';

        $container->privates['EAdmin\\Core\\Command\\TSInstallCommand'] = $instance = new \EAdmin\Core\Command\TSInstallCommand(\dirname(__DIR__, 4));

        $instance->setName('eadmin:ts:install');
        $instance->setDescription('Copy EAdmin config files (vite.config.ts, tsconfig.json) into the project root');

        return $instance;
    }
}
