<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKFrJr5f\EAdmin_Core_Tests_Fixture_TestKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKFrJr5f/EAdmin_Core_Tests_Fixture_TestKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerKFrJr5f.legacy');

    return;
}

if (!\class_exists(EAdmin_Core_Tests_Fixture_TestKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerKFrJr5f\EAdmin_Core_Tests_Fixture_TestKernelTestDebugContainer::class, EAdmin_Core_Tests_Fixture_TestKernelTestDebugContainer::class, false);
}

return new \ContainerKFrJr5f\EAdmin_Core_Tests_Fixture_TestKernelTestDebugContainer([
    'container.build_hash' => 'KFrJr5f',
    'container.build_id' => '5e19988f',
    'container.build_time' => 1786898918,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKFrJr5f');
